<?php

namespace App\Services;

use App\Models\Client;
use App\Models\ClientFundLedger;
use App\Models\ClientPage;
use App\Models\DailyPerformanceReport;
use App\Models\Employee;
use App\Models\EmployeeAssignment;
use App\Models\EmployeeDailySubmission;
use App\Models\EmployeePayroll;
use App\Models\EmployeeWorkStatus;
use App\Models\FacebookCard;
use App\Models\FinanceAccount;
use App\Models\FinanceAccountLedger;
use App\Models\FundingBalance;
use App\Models\SalaryPayment;
use Carbon\Carbon;
use Illuminate\Support\Collection;

class ExecutiveDashboardService
{
    public function __construct(
        private ClientFundSummaryService $clientFunds,
        private ClientFundDashboardService $clientFundDashboard,
        private PayrollCategoryService $payrollCategory,
        private PerformanceOperationsService $performanceOperations
    ) {}

    public function build(array $filters = []): array
    {
        [$from, $to, $label] = $this->period($filters);
        $today = now()->startOfDay();
        $monthStart = now()->startOfMonth();
        $monthEnd = now()->endOfMonth();

        $todayReports = $this->performanceReports($today, $today)->get();
        $monthReports = $this->performanceReports($monthStart, $monthEnd)->get();
        $periodReports = $this->performanceReports($from, $to)->get();
        $fundDashboard = $this->clientFunds->dashboard();
        $legacyFundDashboard = $this->clientFundDashboard->dashboard();
        $payrollRows = $this->payrollCategory->employeeStages();

        return [
            'filters' => [
                'period' => $filters['period'] ?? 'today',
                'date_from' => $from->toDateString(),
                'date_to' => $to->toDateString(),
                'label' => $label,
            ],
            'today' => $this->todayKpis($todayReports, $today, $fundDashboard, $payrollRows),
            'month' => $this->monthKpis($monthReports, $monthStart, $monthEnd, $fundDashboard),
            'finance' => $this->financeSummary($fundDashboard, $legacyFundDashboard, $payrollRows),
            'snapshot' => $this->todaySnapshot($todayReports, $today, $payrollRows),
            'kpi_cards' => $this->kpiCards($fundDashboard, $legacyFundDashboard, $payrollRows),
            'clients' => $this->clientAnalytics($periodReports, $fundDashboard['rows'], $from, $to),
            'pages' => $this->pageAnalytics($periodReports),
            'employees' => $this->employeeAnalytics($from, $to),
            'alerts' => $this->alertCards($fundDashboard, $legacyFundDashboard, $payrollRows),
            'health' => $this->businessHealth($fundDashboard, $legacyFundDashboard, $payrollRows),
            'trends' => $this->trends($filters),
            'recent' => $this->recentActivity(),
            'quick_actions' => $this->quickActions(),
            'search' => $this->globalSearchData(),
            'export_meta' => $this->exportMeta($label, $from, $to),
            'exports' => [
                'csv' => '/admin/executive-performance/export/csv?' . http_build_query($filters),
                'excel' => '/admin/executive-performance/export/excel?' . http_build_query($filters),
                'pdf' => '/admin/executive-performance/export/pdf?' . http_build_query($filters),
            ],
        ];
    }

    public function exportRows(array $filters = []): Collection
    {
        $dashboard = $this->build($filters);

        return collect([
            ['section' => 'Export', 'metric' => 'Company', 'value' => $dashboard['export_meta']['company']],
            ['section' => 'Export', 'metric' => 'Applied Filters', 'value' => $dashboard['export_meta']['filters']],
            ['section' => 'Export', 'metric' => 'Export Timestamp', 'value' => $dashboard['export_meta']['generated_at']],
            ['section' => 'Export', 'metric' => 'Generated By', 'value' => $dashboard['export_meta']['generated_by']],
            ['section' => 'Today', 'metric' => 'Total Orders', 'value' => $dashboard['today']['orders']],
            ['section' => 'Today', 'metric' => 'Total Facebook Spend USD', 'value' => $dashboard['today']['spend_usd']],
            ['section' => 'Today', 'metric' => 'Total Facebook Spend BDT', 'value' => $dashboard['today']['spend_bdt']],
            ['section' => 'Today', 'metric' => 'Total Revenue', 'value' => $dashboard['today']['revenue']],
            ['section' => 'Today', 'metric' => 'Estimated Profit', 'value' => $dashboard['today']['profit']],
            ['section' => 'This Month', 'metric' => 'Total Orders', 'value' => $dashboard['month']['orders']],
            ['section' => 'This Month', 'metric' => 'Total Spend USD', 'value' => $dashboard['month']['spend_usd']],
            ['section' => 'This Month', 'metric' => 'Total Revenue', 'value' => $dashboard['month']['revenue']],
            ['section' => 'This Month', 'metric' => 'Net Profit', 'value' => $dashboard['month']['net_profit']],
            ['section' => 'Finance', 'metric' => 'Salary Fund Balance', 'value' => $dashboard['finance']['salary_fund_balance']],
            ['section' => 'Finance', 'metric' => 'Ads Fund Balance', 'value' => $dashboard['finance']['ads_fund_balance']],
            ['section' => 'Finance', 'metric' => 'Finance Account Balance', 'value' => $dashboard['finance']['finance_account_balance']],
        ]);
    }

    private function todayKpis(Collection $reports, Carbon $today, array $fundDashboard, Collection $payrollRows): array
    {
        $clientPayments = (float) SalaryPayment::where('status', 'approved')
            ->whereDate('approved_at', $today->toDateString())
            ->sum('amount');

        return [
            'orders' => (int) $reports->sum('orders'),
            'spend_usd' => (float) $reports->sum('spend'),
            'spend_bdt' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->actualCost()),
            'revenue' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue()),
            'profit' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->profit()),
            'payroll_paid' => (float) EmployeePayroll::where('payroll_status', 'paid')
                ->whereDate('payment_confirmed_at', $today->toDateString())
                ->sum('paid_amount'),
            'client_payments_received' => $clientPayments,
            'salary_fund_balance' => (float) $fundDashboard['summary']['salary_balance'],
            'ads_fund_balance' => (float) $fundDashboard['summary']['ads_balance'],
            'finance_account_balance' => (float) FinanceAccount::sum('current_balance'),
            'pending_approvals' => $this->pendingApprovalCount($payrollRows),
        ];
    }

    private function monthKpis(Collection $reports, Carbon $from, Carbon $to, array $fundDashboard): array
    {
        $payrollPaid = (float) EmployeePayroll::where('payroll_status', 'paid')
            ->whereBetween('payment_confirmed_at', [$from, $to])
            ->sum('paid_amount');

        return [
            'orders' => (int) $reports->sum('orders'),
            'spend_usd' => (float) $reports->sum('spend'),
            'spend_bdt' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->actualCost()),
            'revenue' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue()),
            'profit' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->profit()),
            'net_profit' => round((float) $reports->sum(fn (DailyPerformanceReport $report) => $report->profit()) - $payrollPaid, 2),
            'payroll_paid' => $payrollPaid,
            'salary_fund_received' => (float) ClientFundLedger::where('fund_type', ClientFundLedger::FUND_EMPLOYEE_SALARY)->where('direction', ClientFundLedger::DIRECTION_CREDIT)->whereBetween('created_at', [$from, $to])->sum('amount_bdt'),
            'salary_fund_used' => (float) ClientFundLedger::where('fund_type', ClientFundLedger::FUND_EMPLOYEE_SALARY)->where('direction', ClientFundLedger::DIRECTION_DEBIT)->whereBetween('created_at', [$from, $to])->sum('amount_bdt'),
            'ads_fund_received' => (float) ClientFundLedger::where('fund_type', ClientFundLedger::FUND_FACEBOOK_ADS)->where('direction', ClientFundLedger::DIRECTION_CREDIT)->whereBetween('created_at', [$from, $to])->sum('amount_bdt'),
            'ads_fund_used' => (float) ClientFundLedger::where('fund_type', ClientFundLedger::FUND_FACEBOOK_ADS)->where('direction', ClientFundLedger::DIRECTION_DEBIT)->whereBetween('created_at', [$from, $to])->sum('amount_bdt'),
            'new_clients' => Client::whereBetween('created_at', [$from, $to])->count(),
            'new_employees' => Employee::whereBetween('created_at', [$from, $to])->count(),
            'current_salary_fund_balance' => (float) $fundDashboard['summary']['salary_balance'],
            'current_ads_fund_balance' => (float) $fundDashboard['summary']['ads_balance'],
        ];
    }

    private function financeSummary(array $fundDashboard, array $legacyFundDashboard, Collection $payrollRows): array
    {
        $funding = FundingBalance::all();
        $cards = FacebookCard::all();
        $financeAccounts = FinanceAccount::all();

        return [
            'finance_accounts' => $financeAccounts->count(),
            'finance_account_balance' => (float) $financeAccounts->sum('current_balance'),
            'binance_balance' => (float) $funding->where('source', 'binance')->sum('current_balance'),
            'facebook_card_balance' => (float) $cards->sum('current_balance'),
            'salary_fund_balance' => (float) $fundDashboard['summary']['salary_balance'],
            'ads_fund_balance' => (float) $fundDashboard['summary']['ads_balance'],
            'outstanding_client_due' => abs((float) $fundDashboard['rows']->sum(fn (array $row) => min((float) $row['funds']['combined_balance'], 0))),
            'outstanding_salary_due' => (float) $legacyFundDashboard['summary']['unpaid_salary_due'],
        ];
    }

    private function todaySnapshot(Collection $reports, Carbon $today, Collection $payrollRows): array
    {
        $clientPayments = (float) SalaryPayment::where('status', 'approved')
            ->whereDate('approved_at', $today->toDateString())
            ->sum('amount');
        $payrollPaid = (float) EmployeePayroll::where('payroll_status', 'paid')
            ->whereDate('payment_confirmed_at', $today->toDateString())
            ->sum('paid_amount');
        $pendingApprovals = $this->pendingApprovalCount($payrollRows);
        $snapshot = [
            [
                'label' => "Today's Orders",
                'value' => (int) $reports->sum('orders'),
                'display' => number_format((int) $reports->sum('orders')),
                'url' => '/admin/executive-performance',
            ],
            [
                'label' => "Today's Spend",
                'value' => (float) $reports->sum('spend'),
                'display' => 'USD ' . number_format((float) $reports->sum('spend'), 2),
                'url' => '/admin/executive-performance',
            ],
            [
                'label' => "Today's Revenue",
                'value' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue()),
                'display' => 'BDT ' . number_format((float) $reports->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue()), 2),
                'url' => '/admin/executive-performance',
            ],
            [
                'label' => "Today's Estimated Profit",
                'value' => (float) $reports->sum(fn (DailyPerformanceReport $report) => $report->profit()),
                'display' => 'BDT ' . number_format((float) $reports->sum(fn (DailyPerformanceReport $report) => $report->profit()), 2),
                'url' => '/admin/facebook-financial/profit-dashboard',
            ],
            [
                'label' => "Today's Client Payments",
                'value' => $clientPayments,
                'display' => 'BDT ' . number_format($clientPayments, 2),
                'url' => '/admin/salary-payments',
            ],
            [
                'label' => "Today's Payroll Paid",
                'value' => $payrollPaid,
                'display' => 'BDT ' . number_format($payrollPaid, 2),
                'url' => '/admin/payroll/payment-report',
            ],
            [
                'label' => "Today's Pending Approvals",
                'value' => $pendingApprovals,
                'display' => number_format($pendingApprovals),
                'url' => '/admin/performance-verification',
            ],
        ];

        return [
            'cards' => collect($snapshot)->map(fn (array $card) => $card + ['tone' => $this->tone((float) $card['value'])])->all(),
            'has_activity' => collect($snapshot)->sum('value') > 0,
        ];
    }

    private function kpiCards(array $fundDashboard, array $legacyFundDashboard, Collection $payrollRows): array
    {
        $finance = $this->financeSummary($fundDashboard, $legacyFundDashboard, $payrollRows);
        $pendingPayroll = EmployeePayroll::where('payroll_status', 'generated')->count();
        $pendingClientPayments = SalaryPayment::where('status', 'pending')->count();
        $missingWorkStatus = $payrollRows->where('stage.category', PayrollCategoryService::PENDING_WORK_STATUS)->count();
        $assignmentExpired = EmployeeAssignment::where('status', 'active')
            ->whereNotNull('assigned_to')
            ->whereDate('assigned_to', '<', now()->toDateString())
            ->count();
        $month = $this->monthKpis(
            $this->performanceReports(now()->startOfMonth(), now()->endOfMonth())->get(),
            now()->startOfMonth(),
            now()->endOfMonth(),
            $fundDashboard
        );

        return collect([
            ['label' => 'Employee Salary Fund Balance', 'value' => $finance['salary_fund_balance'], 'display' => 'BDT ' . number_format($finance['salary_fund_balance'], 2), 'url' => '/admin/client-fund'],
            ['label' => 'Facebook Ads Fund Balance', 'value' => $finance['ads_fund_balance'], 'display' => 'BDT ' . number_format($finance['ads_fund_balance'], 2), 'url' => '/admin/client-fund'],
            ['label' => 'Net Profit', 'value' => $month['net_profit'], 'display' => 'BDT ' . number_format($month['net_profit'], 2), 'url' => '/admin/facebook-financial/profit-dashboard'],
            ['label' => 'Outstanding Client Due', 'value' => -1 * $finance['outstanding_client_due'], 'display' => 'BDT ' . number_format($finance['outstanding_client_due'], 2), 'url' => '/admin/clients'],
            ['label' => 'Outstanding Salary Due', 'value' => -1 * $finance['outstanding_salary_due'], 'display' => 'BDT ' . number_format($finance['outstanding_salary_due'], 2), 'url' => '/admin/payroll?status=due'],
            ['label' => 'Pending Payroll', 'value' => $pendingPayroll, 'display' => number_format($pendingPayroll), 'url' => '/admin/payroll?status=generated'],
            ['label' => 'Pending Client Payments', 'value' => $pendingClientPayments, 'display' => number_format($pendingClientPayments), 'url' => '/admin/salary-payments/pending'],
            ['label' => 'Missing Work Status', 'value' => -1 * $missingWorkStatus, 'display' => number_format($missingWorkStatus), 'url' => '/admin/work-status'],
            ['label' => 'Assignment Expired', 'value' => -1 * $assignmentExpired, 'display' => number_format($assignmentExpired), 'url' => '/admin/assignments'],
            ['label' => 'Finance Balance', 'value' => $finance['finance_account_balance'], 'display' => 'BDT ' . number_format($finance['finance_account_balance'], 2), 'url' => '/admin/finance/accounts'],
            ['label' => 'Client Payments', 'value' => SalaryPayment::where('status', 'approved')->count(), 'display' => number_format(SalaryPayment::where('status', 'approved')->count()), 'url' => '/admin/salary-payments'],
        ])->map(fn (array $card) => $card + ['tone' => $this->tone((float) $card['value'])])->all();
    }

    private function clientAnalytics(Collection $reports, Collection $fundRows, Carbon $from, Carbon $to): array
    {
        $byClient = $reports->groupBy(fn (DailyPerformanceReport $report) => $report->campaign?->client_id ?: 0)
            ->map(function (Collection $items) {
                $sample = $items->first();
                $spend = (float) $items->sum('spend');
                $orders = (int) $items->sum('orders');

                return [
                    'client' => $sample?->campaign?->client,
                    'spend' => $spend,
                    'orders' => $orders,
                    'revenue' => (float) $items->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue()),
                    'profit' => (float) $items->sum(fn (DailyPerformanceReport $report) => $report->profit()),
                    'cpo' => DailyPerformanceReport::costPer($spend, $orders),
                ];
            })
            ->filter(fn (array $row) => $row['client'])
            ->values();

        $balances = $fundRows->map(fn (array $row) => [
            'client' => $row['client'],
            'balance' => (float) $row['funds']['combined_balance'],
            'due' => abs(min((float) $row['funds']['combined_balance'], 0)),
        ]);

        $previousFrom = $from->copy()->subDays($from->diffInDays($to) + 1);
        $previousTo = $from->copy()->subDay()->endOfDay();
        $previousRevenue = $this->performanceReports($previousFrom, $previousTo)
            ->get()
            ->groupBy(fn (DailyPerformanceReport $report) => $report->campaign?->client_id ?: 0)
            ->map(fn (Collection $items) => (float) $items->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue()));
        $growth = $byClient->map(function (array $row) use ($previousRevenue) {
            $previous = (float) $previousRevenue->get($row['client']->id, 0);

            return $row + [
                'growth' => round((float) $row['revenue'] - $previous, 2),
                'trend' => $row['revenue'] > $previous ? 'Up' : ($row['revenue'] < $previous ? 'Down' : 'Stable'),
            ];
        });

        return [
            'highest_revenue' => $byClient->sortByDesc('revenue')->take(5)->values(),
            'highest_spend' => $byClient->sortByDesc('spend')->take(5)->values(),
            'highest_profit' => $byClient->sortByDesc('profit')->take(5)->values(),
            'highest_due' => $balances->sortByDesc('due')->take(5)->values(),
            'highest_orders' => $byClient->sortByDesc('orders')->take(5)->values(),
            'highest_growth' => $growth->sortByDesc('growth')->take(5)->values(),
        ];
    }

    private function pageAnalytics(Collection $reports): array
    {
        $rows = $reports->groupBy(fn (DailyPerformanceReport $report) => $report->campaign?->client_page_id ?: 0)
            ->map(function (Collection $items) {
                $sample = $items->first();
                $spend = (float) $items->sum('spend');
                $orders = (int) $items->sum('orders');
                $revenue = (float) $items->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue());

                return [
                    'page' => $sample?->campaign?->page,
                    'orders' => $orders,
                    'spend' => $spend,
                    'cpo' => DailyPerformanceReport::costPer($spend, $orders),
                    'revenue' => $revenue,
                    'profit' => (float) $items->sum(fn (DailyPerformanceReport $report) => $report->profit()),
                    'conversion' => $spend > 0 ? round($orders / $spend, 2) : 0,
                ];
            })
            ->filter(fn (array $row) => $row['page'])
            ->values();

        return [
            'top' => $rows->sortByDesc('orders')->take(8)->values(),
            'lowest' => $rows->sortBy([['orders', 'asc'], ['spend', 'desc']])->take(8)->values(),
        ];
    }

    private function employeeAnalytics(Carbon $from, Carbon $to): array
    {
        $kpis = $this->performanceOperations->kpiRows($from, $to);

        return [
            'top_moderator' => $kpis->sortByDesc('confirmed_orders')->first(),
            'top_ad_manager' => $kpis->sortByDesc('approved_spend')->first(),
            'top_performer' => $kpis->sortByDesc('profit_contribution')->first(),
            'lowest_performer' => $kpis->sortBy('approval_rate')->first(),
            'approval_rate' => round((float) $kpis->avg('approval_rate'), 2),
            'average_orders' => round((float) $kpis->avg('average_orders'), 2),
            'average_spend' => round((float) $kpis->avg('average_spend'), 2),
            'average_productivity' => round((float) $kpis->avg('target_achievement'), 2),
            'pending_reviews' => EmployeeDailySubmission::where('status', 'pending')
                ->whereDate('submission_date', '>=', $from->toDateString())
                ->whereDate('submission_date', '<=', $to->toDateString())
                ->count(),
        ];
    }

    private function alerts(array $fundDashboard, array $legacyFundDashboard, Collection $payrollRows): array
    {
        $today = now()->startOfDay();

        return [
            'negative_salary_fund' => $fundDashboard['rows']->filter(fn (array $row) => (float) $row['funds']['salary']['balance'] < 0)->count(),
            'negative_ads_fund' => $fundDashboard['rows']->filter(fn (array $row) => (float) $row['funds']['ads']['balance'] < 0)->count(),
            'low_finance_accounts' => FinanceAccount::where('status', 'active')->where('current_balance', '<', 1000)->count(),
            'upcoming_salary' => $this->payrollCategory->upcomingCycles($today)->count(),
            'unpaid_salary' => $payrollRows->whereIn('stage.category', [PayrollCategoryService::UNPAID, PayrollCategoryService::FINAL_SETTLEMENT_UNPAID])->count(),
            'pending_daily_performance_merge' => $this->performanceOperations->verificationGroups(['date_from' => $today->copy()->subDays(30)->toDateString(), 'date_to' => $today->toDateString()])->where('status', 'ready_to_merge')->count(),
            'pending_client_payments' => SalaryPayment::where('status', 'pending')->count(),
            'pending_payroll_approval' => EmployeePayroll::where('payroll_status', 'generated')->count(),
            'missing_work_status' => $payrollRows->where('stage.category', PayrollCategoryService::PENDING_WORK_STATUS)->count(),
            'assignment_expired' => EmployeeAssignment::where('status', 'active')->whereNotNull('assigned_to')->whereDate('assigned_to', '<', $today->toDateString())->count(),
            'outstanding_salary_due' => (float) $legacyFundDashboard['summary']['unpaid_salary_due'],
        ];
    }

    private function alertCards(array $fundDashboard, array $legacyFundDashboard, Collection $payrollRows): array
    {
        $alerts = $this->alerts($fundDashboard, $legacyFundDashboard, $payrollRows);

        return [
            ['key' => 'negative_ads_fund', 'label' => 'Clients with Negative Ads Fund', 'count' => $alerts['negative_ads_fund'], 'severity' => 'HIGH', 'explanation' => 'Ads fund balance is below zero.', 'url' => '/admin/client-fund'],
            ['key' => 'negative_salary_fund', 'label' => 'Clients with Negative Salary Fund', 'count' => $alerts['negative_salary_fund'], 'severity' => 'HIGH', 'explanation' => 'Employee salary fund is below zero.', 'url' => '/admin/client-fund'],
            ['key' => 'unpaid_salary', 'label' => 'Unpaid Salary', 'count' => $alerts['unpaid_salary'], 'severity' => 'HIGH', 'explanation' => 'Payroll items still need settlement.', 'url' => '/admin/payroll?status=due'],
            ['key' => 'upcoming_salary', 'label' => 'Upcoming Salary', 'count' => $alerts['upcoming_salary'], 'severity' => 'MEDIUM', 'explanation' => 'Salary cycles due within five days.', 'url' => '/admin/payroll/upcoming'],
            ['key' => 'pending_daily_performance_merge', 'label' => 'Ready Performance Merge', 'count' => $alerts['pending_daily_performance_merge'], 'severity' => 'MEDIUM', 'explanation' => 'Approved order and spend pairs are ready.', 'url' => '/admin/performance-verification'],
            ['key' => 'pending_client_payments', 'label' => 'Pending Client Payments', 'count' => $alerts['pending_client_payments'], 'severity' => 'MEDIUM', 'explanation' => 'Client fund payments need approval.', 'url' => '/admin/salary-payments/pending'],
            ['key' => 'pending_payroll_approval', 'label' => 'Pending Payroll Approval', 'count' => $alerts['pending_payroll_approval'], 'severity' => 'MEDIUM', 'explanation' => 'Generated payroll needs approval.', 'url' => '/admin/payroll?status=generated'],
            ['key' => 'missing_work_status', 'label' => 'Missing Work Status', 'count' => $alerts['missing_work_status'], 'severity' => 'MEDIUM', 'explanation' => 'Salary cycles need work status records.', 'url' => '/admin/work-status'],
            ['key' => 'assignment_expired', 'label' => 'Assignment Expired', 'count' => $alerts['assignment_expired'], 'severity' => 'LOW', 'explanation' => 'Assignments have passed their end date.', 'url' => '/admin/assignments'],
            ['key' => 'low_finance_accounts', 'label' => 'Low Finance Accounts', 'count' => $alerts['low_finance_accounts'], 'severity' => 'LOW', 'explanation' => 'Active finance accounts are below threshold.', 'url' => '/admin/finance/accounts'],
        ];
    }

    private function businessHealth(array $fundDashboard, array $legacyFundDashboard, Collection $payrollRows): array
    {
        $alerts = $this->alerts($fundDashboard, $legacyFundDashboard, $payrollRows);
        $critical = $alerts['negative_salary_fund'] + $alerts['negative_ads_fund'] + $alerts['unpaid_salary'];
        $warning = $alerts['pending_daily_performance_merge'] + $alerts['pending_client_payments'] + $alerts['missing_work_status'] + $alerts['assignment_expired'];

        if ($critical > 0) {
            $status = 'Critical';
            $tone = 'negative';
        } elseif ($warning > 0) {
            $status = 'Warning';
            $tone = 'warning';
        } elseif ($alerts['upcoming_salary'] > 0) {
            $status = 'Good';
            $tone = 'positive';
        } else {
            $status = 'Excellent';
            $tone = 'positive';
        }

        return [
            'status' => $status,
            'tone' => $tone,
            'critical_count' => $critical,
            'warning_count' => $warning,
            'checks' => [
                ['label' => 'Negative balances', 'count' => $alerts['negative_salary_fund'] + $alerts['negative_ads_fund']],
                ['label' => 'Pending approvals', 'count' => $this->pendingApprovalCount($payrollRows)],
                ['label' => 'Outstanding salary', 'count' => $alerts['unpaid_salary']],
                ['label' => 'Missing work status', 'count' => $alerts['missing_work_status']],
                ['label' => 'Expired assignments', 'count' => $alerts['assignment_expired']],
            ],
        ];
    }

    private function trends(array $filters = []): array
    {
        [$start, $end] = $this->trendPeriod($filters);
        $reports = $this->performanceReports($start, $end)->get()->groupBy(fn (DailyPerformanceReport $report) => $report->report_date->toDateString());
        $fundLedgers = ClientFundLedger::whereBetween('created_at', [$start, $end])->get()->groupBy(fn (ClientFundLedger $ledger) => $ledger->created_at->toDateString());
        $payrollLedgers = FinanceAccountLedger::where('transaction_type', 'salary_payment')->whereBetween('created_at', [$start, $end])->get()->groupBy(fn (FinanceAccountLedger $ledger) => $ledger->created_at->toDateString());
        $clientPaymentLedgers = FinanceAccountLedger::where('transaction_type', 'client_payment')->whereBetween('created_at', [$start, $end])->get()->groupBy(fn (FinanceAccountLedger $ledger) => $ledger->created_at->toDateString());

        return collect(range(0, max($start->diffInDays($end), 0)))->map(function (int $offset) use ($start, $reports, $fundLedgers, $payrollLedgers, $clientPaymentLedgers) {
            $date = $start->copy()->addDays($offset)->toDateString();
            $dailyReports = $reports->get($date, collect());
            $dailyFunds = $fundLedgers->get($date, collect());

            return [
                'date' => $date,
                'orders' => (int) $dailyReports->sum('orders'),
                'spend' => (float) $dailyReports->sum('spend'),
                'revenue' => (float) $dailyReports->sum(fn (DailyPerformanceReport $report) => $report->clientRevenue()),
                'profit' => (float) $dailyReports->sum(fn (DailyPerformanceReport $report) => $report->profit()),
                'salary_fund' => (float) $dailyFunds->where('fund_type', ClientFundLedger::FUND_EMPLOYEE_SALARY)->sum('amount_bdt'),
                'ads_fund' => (float) $dailyFunds->where('fund_type', ClientFundLedger::FUND_FACEBOOK_ADS)->sum('amount_bdt'),
                'client_payments' => (float) $clientPaymentLedgers->get($date, collect())->sum('amount'),
                'payroll_payments' => (float) $payrollLedgers->get($date, collect())->sum('amount'),
            ];
        })->values()->all();
    }

    private function recentActivity(): array
    {
        return collect([
            SalaryPayment::with('client')->latest()->limit(5)->get()->map(fn (SalaryPayment $payment) => [
                'time' => $payment->created_at,
                'label' => 'Client Payment Received',
                'detail' => ($payment->client?->company_name ?? 'Client') . ' | BDT ' . number_format((float) $payment->amount, 2),
                'url' => '/admin/salary-payments',
            ]),
            EmployeePayroll::with('employee')->where('payroll_status', 'paid')->latest('payment_confirmed_at')->limit(5)->get()->map(fn (EmployeePayroll $payroll) => [
                'time' => $payroll->payment_confirmed_at ?: $payroll->updated_at,
                'label' => 'Payroll Confirmed',
                'detail' => ($payroll->employee?->name ?? 'Employee') . ' | BDT ' . number_format((float) $payroll->paid_amount, 2),
                'url' => '/admin/payroll/' . $payroll->id,
            ]),
            DailyPerformanceReport::with('campaign.client')->whereNotNull('merged_at')->latest('merged_at')->limit(5)->get()->map(fn (DailyPerformanceReport $report) => [
                'time' => $report->merged_at,
                'label' => 'Daily Performance Merged',
                'detail' => ($report->campaign?->client?->company_name ?? 'Client') . ' | ' . number_format((int) $report->orders) . ' orders',
                'url' => '/admin/executive-performance',
            ]),
            EmployeeDailySubmission::with('employee')->whereIn('status', ['approved', 'merged'])->latest('reviewed_at')->limit(5)->get()->map(fn (EmployeeDailySubmission $submission) => [
                'time' => $submission->reviewed_at ?: $submission->updated_at,
                'label' => 'Employee Submission Approved',
                'detail' => ($submission->employee?->name ?? 'Employee') . ' | ' . $submission->statusLabel(),
                'url' => '/admin/performance-verification',
            ]),
            EmployeeAssignment::with(['employee', 'client'])->latest()->limit(5)->get()->map(fn (EmployeeAssignment $assignment) => [
                'time' => $assignment->updated_at,
                'label' => 'Assignment Updated',
                'detail' => ($assignment->employee?->name ?? 'Employee') . ' | ' . ($assignment->client?->company_name ?? 'No client'),
                'url' => '/admin/assignments',
            ]),
        ])->flatten(1)
            ->filter(fn (array $item) => $item['time'])
            ->sortByDesc('time')
            ->take(20)
            ->values()
            ->all();
    }

    private function quickActions(): array
    {
        return [
            'Finance' => [
                ['label' => 'Receive Client Payment', 'url' => '/admin/salary-payments/create', 'icon' => 'BDT'],
                ['label' => 'Finance Accounts', 'url' => '/admin/finance/accounts', 'icon' => 'FA'],
            ],
            'Payroll' => [
                ['label' => 'Approve Payroll', 'url' => '/admin/payroll?status=generated', 'icon' => 'PR'],
                ['label' => 'Salary Report', 'url' => '/admin/payroll/payment-report', 'icon' => 'SR'],
            ],
            'Performance' => [
                ['label' => 'Performance Verification', 'url' => '/admin/performance-verification', 'icon' => 'PV'],
                ['label' => 'Campaigns', 'url' => '/admin/campaigns', 'icon' => 'CM'],
            ],
            'Employee' => [
                ['label' => 'Employees', 'url' => '/admin/employees', 'icon' => 'EM'],
                ['label' => 'Assignments', 'url' => '/admin/assignments', 'icon' => 'AS'],
            ],
            'Client' => [
                ['label' => 'Client Management', 'url' => '/admin/clients', 'icon' => 'CL'],
                ['label' => 'Client Fund', 'url' => '/admin/client-fund', 'icon' => 'CF'],
            ],
            'System' => [
                ['label' => 'Activity Log', 'url' => '/admin/activity-log', 'icon' => 'AL'],
                ['label' => 'Bug Tracker', 'url' => '/admin/bug-tracker', 'icon' => 'BT'],
            ],
        ];
    }

    private function globalSearchData(): array
    {
        return [
            'clients' => Client::orderBy('company_name')->limit(8)->get(['id', 'company_name']),
            'employees' => Employee::orderBy('name')->limit(8)->get(['id', 'employee_id', 'name']),
            'pages' => ClientPage::orderBy('page_name')->limit(8)->get(['id', 'page_name']),
            'campaigns' => \App\Models\Campaign::orderBy('campaign_name')->limit(8)->get(['id', 'campaign_name', 'campaign_id']),
            'finance_accounts' => FinanceAccount::orderBy('account_name')->limit(8)->get(['id', 'account_name', 'currency']),
            'assignments' => EmployeeAssignment::with(['employee', 'client'])->latest()->limit(8)->get(),
        ];
    }

    private function performanceReports(Carbon $from, Carbon $to)
    {
        return DailyPerformanceReport::with(['campaign.client', 'campaign.page'])
            ->whereDate('report_date', '>=', $from->toDateString())
            ->whereDate('report_date', '<=', $to->toDateString());
    }

    private function pendingApprovalCount(Collection $payrollRows): int
    {
        return EmployeeDailySubmission::where('status', 'pending')->count()
            + SalaryPayment::where('status', 'pending')->count()
            + EmployeePayroll::where('payroll_status', 'generated')->count()
            + $payrollRows->where('stage.category', PayrollCategoryService::SALARY_READY)->count();
    }

    private function period(array $filters): array
    {
        $period = $filters['period'] ?? 'today';

        return match ($period) {
            '7_days' => [now()->subDays(6)->startOfDay(), now()->endOfDay(), 'Last 7 Days'],
            '30_days' => [now()->subDays(29)->startOfDay(), now()->endOfDay(), 'Last 30 Days'],
            'yesterday' => [now()->subDay()->startOfDay(), now()->subDay()->endOfDay(), 'Yesterday'],
            'this_week' => [now()->startOfWeek(), now()->endOfWeek(), 'This Week'],
            'this_month' => [now()->startOfMonth(), now()->endOfMonth(), 'This Month'],
            'last_month' => [now()->subMonthNoOverflow()->startOfMonth(), now()->subMonthNoOverflow()->endOfMonth(), 'Last Month'],
            'custom' => [
                Carbon::parse($filters['date_from'] ?? now()->toDateString())->startOfDay(),
                Carbon::parse($filters['date_to'] ?? now()->toDateString())->endOfDay(),
                'Custom',
            ],
            default => [now()->startOfDay(), now()->endOfDay(), 'Today'],
        };
    }

    private function tone(float $value): string
    {
        if ($value < 0) {
            return 'negative';
        }

        if ($value > 0) {
            return 'positive';
        }

        return 'neutral';
    }

    private function trendPeriod(array $filters): array
    {
        return match ($filters['period'] ?? '30_days') {
            '7_days' => [now()->subDays(6)->startOfDay(), now()->endOfDay()],
            'this_month' => [now()->startOfMonth(), now()->endOfMonth()],
            'custom' => [
                Carbon::parse($filters['date_from'] ?? now()->subDays(29)->toDateString())->startOfDay(),
                Carbon::parse($filters['date_to'] ?? now()->toDateString())->endOfDay(),
            ],
            default => [now()->subDays(29)->startOfDay(), now()->endOfDay()],
        };
    }

    private function exportMeta(string $label, Carbon $from, Carbon $to): array
    {
        return [
            'company' => 'NSYS Lab',
            'filters' => $label . ': ' . $from->toDateString() . ' to ' . $to->toDateString(),
            'generated_at' => now()->format('Y-m-d H:i:s'),
            'generated_by' => auth()->user()?->name ?? auth()->user()?->email ?? 'System',
        ];
    }
}
