<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Client Statement</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111827;
        }

        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }

        .brand {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
        }

        .muted {
            color: #6b7280;
        }

        h2 {
            margin-top: 22px;
            color: #111827;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background: #f3f4f6;
            text-align: left;
        }

        th, td {
            border: 1px solid #d1d5db;
            padding: 7px;
            vertical-align: top;
        }

        .summary td {
            font-weight: bold;
        }

        .positive {
            color: #16a34a;
            font-weight: bold;
        }

        .negative {
            color: #dc2626;
            font-weight: bold;
        }

        .footer {
            margin-top: 28px;
            font-size: 10px;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="brand">NSYS Agency</div>
        <div class="muted">Client Financial Statement</div>
        <div class="muted">Generated Date: {{ date('Y-m-d') }}</div>
    </div>

    <h2>Client Information</h2>
    <table>
        <tr>
            <th>Client Name</th>
            <td>{{ $client->company_name }}</td>
            <th>Phone</th>
            <td>{{ $client->phone ?: 'N/A' }}</td>
        </tr>
        <tr>
            <th>Client Rate</th>
            <td>BDT {{ number_format($summary['client_rate'], 2) }}</td>
            <th>Buy Rate</th>
            <td>BDT {{ number_format($summary['buy_rate'], 2) }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td colspan="3">{{ ucfirst($client->status) }}</td>
        </tr>
    </table>

    <h2>Financial Summary</h2>
    <table class="summary">
        <tr>
            <th>Total Spend USD</th>
            <th>Total Debit</th>
            <th>Total Credit</th>
            <th>Current Due</th>
            <th>Available Balance</th>
            <th>Profit</th>
        </tr>
        <tr>
            <td>USD {{ number_format($summary['total_spend_usd'], 2) }}</td>
            <td>BDT {{ number_format($summary['total_debit'], 2) }}</td>
            <td>BDT {{ number_format($summary['total_credit'], 2) }}</td>
            <td class="negative">BDT {{ number_format($summary['current_due'], 2) }}</td>
            <td class="positive">BDT {{ number_format($summary['available_balance'], 2) }}</td>
            <td>BDT {{ number_format($summary['profit'], 2) }}</td>
        </tr>
    </table>

    <h2>Ledger</h2>
    <table>
        <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Page</th>
            <th>Invoice</th>
            <th>Orders</th>
            <th>Spend USD</th>
            <th>Debit</th>
            <th>Credit</th>
            <th>Running Due Balance</th>
        </tr>

        @forelse($ledger['rows'] as $row)
            <tr>
                <td>{{ $row['date'] }}</td>
                <td>{{ $row['transaction_type'] }}</td>
                <td>{{ $row['page'] }}</td>
                <td>{{ $row['invoice_number'] ?: '-' }}</td>
                <td>{{ $row['orders'] ?? '-' }}</td>
                <td>{{ $row['spend_usd'] !== null ? 'USD ' . number_format($row['spend_usd'], 2) : '-' }}</td>
                <td>BDT {{ number_format($row['debit'], 2) }}</td>
                <td>BDT {{ number_format($row['credit'], 2) }}</td>
                <td>
                    @if($row['running_balance'] >= 0)
                        BDT {{ number_format($row['running_balance'], 2) }}
                    @else
                        -BDT {{ number_format(abs($row['running_balance']), 2) }}
                    @endif
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="9">No ledger entries found.</td>
            </tr>
        @endforelse
    </table>

    <div class="footer">
        This statement was generated by NSYS Agency Portal.
    </div>
</body>
</html>
