<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Client Statement</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #111827;
        }

        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }

        .brand {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
        }

        .muted {
            color: #6b7280;
        }

        h2 {
            margin-top: 25px;
            color: #111827;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background: #f3f4f6;
            text-align: left;
        }

        th, td {
            border: 1px solid #d1d5db;
            padding: 8px;
        }

        .summary td {
            font-weight: bold;
        }

        .positive {
            color: #16a34a;
            font-weight: bold;
        }

        .negative {
            color: #dc2626;
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            font-size: 11px;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="brand">NSYS Agency</div>
        <div class="muted">Client Financial Statement</div>
        <div class="muted">Generated Date: {{ date('Y-m-d') }}</div>
    </div>

    <h2>Client Information</h2>
    <table>
        <tr>
            <th>Client Name</th>
            <td>{{ $client->company_name }}</td>
        </tr>
        <tr>
            <th>Phone</th>
            <td>{{ $client->phone }}</td>
        </tr>
        <tr>
            <th>Client Rate</th>
            <td>{{ $client->client_rate }}</td>
        </tr>
        <tr>
            <th>Buy Rate</th>
            <td>{{ $client->buy_rate }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{{ ucfirst($client->status) }}</td>
        </tr>
    </table>

    <h2>Financial Summary</h2>
    <table class="summary">
        <tr>
            <th>Approved Payment</th>
            <th>Total Spend USD</th>
            <th>Total Spend BDT</th>
            <th>Balance</th>
        </tr>
        <tr>
            <td>BDT {{ number_format($approvedPayment, 2) }}</td>
            <td>USD {{ number_format($totalDollarSpend, 2) }}</td>
            <td>BDT {{ number_format($totalSpendBdt, 2) }}</td>
            <td>
                @if($balance >= 0)
                    <span class="positive">BDT {{ number_format($balance, 2) }}</span>
                @else
                    <span class="negative">-BDT {{ number_format(abs($balance), 2) }}</span>
                @endif
            </td>
        </tr>
    </table>

    <h2>Payment History</h2>
    <table>
        <tr>
            <th>ID</th>
            <th>Amount</th>
            <th>Method</th>
            <th>Transaction ID</th>
            <th>Status</th>
            <th>Date</th>
        </tr>

        @forelse($payments as $payment)
            <tr>
                <td>{{ $payment->id }}</td>
                <td>BDT {{ number_format($payment->amount, 2) }}</td>
                <td>{{ $payment->payment_method }}</td>
                <td>{{ $payment->transaction_id }}</td>
                <td>{{ ucfirst($payment->status) }}</td>
                <td>{{ $payment->created_at }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="6">No payment history found.</td>
            </tr>
        @endforelse
    </table>

    <h2>Daily Report History</h2>
    <table>
        <tr>
            <th>ID</th>
            <th>Date</th>
            <th>Page</th>
            <th>Spend USD</th>
            <th>Orders</th>
        </tr>

        @forelse($reports as $report)
            <tr>
                <td>{{ $report->id }}</td>
                <td>{{ $report->report_date }}</td>
                <td>{{ $report->page_name }}</td>
                <td>USD {{ number_format($report->dollar_spend, 2) }}</td>
                <td>{{ $report->orders }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5">No report history found.</td>
            </tr>
        @endforelse
    </table>

    <div class="footer">
        This statement was generated by NSYS Agency Portal.
    </div>
</body>
</html>